spring:
  application:
    name: product
  datasource:
           driver-class-name: com.mysql.jdbc.Driver
           username: root
           password: 123456
           url: jdbc:mysql://192.168.43.118:3306/order?useUnicode=true&characterEncoding=UTF-8&useSSL=false
eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
server:
  port: 8082
